version: '3.8'

services:
  grobid:
    image: lfoppiano/grobid:0.8.0
    container_name: rag_book_bot_grobid
    ports:
      - "8070:8070"
    environment:
      - GROBID_HOME=/opt/grobid/grobid-home
    volumes:
      - grobid-data:/opt/grobid/grobid-home/tmp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/api/isalive"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  grobid-data:
    driver: local
